version: '3.8'

services:
  db:
    image: postgres:16-apline
    container_name: brevly-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=brevly
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata: