FROM node:18-alpine AS builder
WORKDIR /app

COPY package*.json ./

RUN npm install --only=production

COPY . .

RUN npm install -g typescript
RUN tsc

FROM node:18-alpine AS runner
WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules

COPY --from=builder /app/dist ./dist

EXPOSE 3333

CMD [ "node", "dist/server.js" ]